### PR TITLE
Add online registration work-flow to website and to admin

### PR DESCRIPTION
**Pull request by BransonGitomeh**
### Goal of Flow

this branch's goal is to make and mentain an online registration process for users to register to the university and the admin to filter through the students that have registered and mark them as selected for the next intake,

### CODE REVIEW

**Comment by BransonGitomeh** [comment]
##programatically this will involve the following model additions

* Student's registration object -> every student account will have it, so as to show what university that student is registered to.When a student registers to a certain university, or two in any case this data about this registration process will be saved here. The status of this process will also be saved here wherether the registration has been revirewed, approved for next intake or rejected will show on the students account
* University registered List -> every university will have one to store the students that have registered to that university , this may/will belong to a certain intake which optionally will be made dynamically on schedule and students can register for the intake, this list is what they will use to select the students that will proceed to be in the school or will not, any action against any student in the list will show on the student's account

**Comment by gideon-maina** [comment]
For the students Object we want to get the information pertaining to that specific student.

For the University Registered List we want to show all the information that pertains to the given University.

**Comment by BransonGitomeh** [comment]
an intake is an instance where the university wants to register new students, students then register for that intake and the university chooses them to be in the next semester as freshers or as new students for a certain course

**Comment by gideon-maina** [comment]
An INTAKE will be interpreted as an action of Registering new students and recording all their properties, actions and changes thereon up to the final year of study

**Comment by BransonGitomeh** [comment]
yeap...but i beleive there is a fundermental diffrence bettween **registering** students and **registatering to be selected** for the next registration

**Comment by BransonGitomeh** [comment]
so now you can fill the registration form, and the student will appear in the registration section in the admin, 

###known bugs
*due to the component reuse, there is an arror related to registering a view that exixsts which breaks the applicationroute hydrating the curent user and uni

**Comment by BransonGitomeh** [comment]
will be fixing soon,

**Comment by BransonGitomeh** [comment]
yeea it was a datepicker id error, fixed it....works like magic now......no breaks, no deprecations

**Pull request merged**
